services:
  postgres:
    container_name: we-spend-api-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: we-spend-api
      PG_DATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres